package com.zw.cjl.network;

public enum HttpGetType {
	GET_TYPE_INVALID,
	GET_ASSISTANT_DETAIL,
	GET_ALL_CAR_NUM,
	GET_ALL_CARS,
	GET_CAR_DETAIL,
	GET_ALL_STUDENT_NUM,
	GET_ALL_STUDENTS,
	GET_ALL_COACH_NUM,
	GET_ALL_COACHS,
}
